# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='email',
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
